// Mocks generated by Mockito 5.4.6 from annotations
// in voidweaver/test/services/scrobble_queue_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;
import 'package:voidweaver/services/network_config.dart' as _i2;
import 'package:voidweaver/services/subsonic_api.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeNetworkConfig_0 extends _i1.SmartFake implements _i2.NetworkConfig {
  _FakeNetworkConfig_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAlbum_1 extends _i1.SmartFake implements _i3.Album {
  _FakeAlbum_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSearchResult_2 extends _i1.SmartFake implements _i3.SearchResult {
  _FakeSearchResult_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SubsonicApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockSubsonicApi extends _i1.Mock implements _i3.SubsonicApi {
  MockSubsonicApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get serverUrl => (super.noSuchMethod(
        Invocation.getter(#serverUrl),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#serverUrl),
        ),
      ) as String);

  @override
  String get username => (super.noSuchMethod(
        Invocation.getter(#username),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#username),
        ),
      ) as String);

  @override
  String get password => (super.noSuchMethod(
        Invocation.getter(#password),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#password),
        ),
      ) as String);

  @override
  String get clientName => (super.noSuchMethod(
        Invocation.getter(#clientName),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#clientName),
        ),
      ) as String);

  @override
  String get version => (super.noSuchMethod(
        Invocation.getter(#version),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#version),
        ),
      ) as String);

  @override
  _i2.NetworkConfig get networkConfig => (super.noSuchMethod(
        Invocation.getter(#networkConfig),
        returnValue: _FakeNetworkConfig_0(
          this,
          Invocation.getter(#networkConfig),
        ),
      ) as _i2.NetworkConfig);

  @override
  bool get hasRetryCapability => (super.noSuchMethod(
        Invocation.getter(#hasRetryCapability),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<List<_i3.Album>> getAlbumList() => (super.noSuchMethod(
        Invocation.method(
          #getAlbumList,
          [],
        ),
        returnValue: _i5.Future<List<_i3.Album>>.value(<_i3.Album>[]),
      ) as _i5.Future<List<_i3.Album>>);

  @override
  _i5.Future<_i3.Album> getAlbum(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getAlbum,
          [id],
        ),
        returnValue: _i5.Future<_i3.Album>.value(_FakeAlbum_1(
          this,
          Invocation.method(
            #getAlbum,
            [id],
          ),
        )),
      ) as _i5.Future<_i3.Album>);

  @override
  _i5.Future<List<_i3.Song>> getRandomSongs([int? count = 50]) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRandomSongs,
          [count],
        ),
        returnValue: _i5.Future<List<_i3.Song>>.value(<_i3.Song>[]),
      ) as _i5.Future<List<_i3.Song>>);

  @override
  String getStreamUrl(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getStreamUrl,
          [id],
        ),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.method(
            #getStreamUrl,
            [id],
          ),
        ),
      ) as String);

  @override
  String getCoverArtUrl(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getCoverArtUrl,
          [id],
        ),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.method(
            #getCoverArtUrl,
            [id],
          ),
        ),
      ) as String);

  @override
  _i5.Future<void> scrobbleNowPlaying(String? songId) => (super.noSuchMethod(
        Invocation.method(
          #scrobbleNowPlaying,
          [songId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> scrobbleSubmission(
    String? songId, {
    DateTime? playedAt,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #scrobbleSubmission,
          [songId],
          {#playedAt: playedAt},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i3.SearchResult> search(
    String? query, {
    int? artistCount = 20,
    int? albumCount = 20,
    int? songCount = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #search,
          [query],
          {
            #artistCount: artistCount,
            #albumCount: albumCount,
            #songCount: songCount,
          },
        ),
        returnValue: _i5.Future<_i3.SearchResult>.value(_FakeSearchResult_2(
          this,
          Invocation.method(
            #search,
            [query],
            {
              #artistCount: artistCount,
              #albumCount: albumCount,
              #songCount: songCount,
            },
          ),
        )),
      ) as _i5.Future<_i3.SearchResult>);

  @override
  _i5.Future<List<_i3.Artist>> getArtists() => (super.noSuchMethod(
        Invocation.method(
          #getArtists,
          [],
        ),
        returnValue: _i5.Future<List<_i3.Artist>>.value(<_i3.Artist>[]),
      ) as _i5.Future<List<_i3.Artist>>);

  @override
  _i5.Future<List<_i3.Album>> getArtistAlbums(String? artistId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getArtistAlbums,
          [artistId],
        ),
        returnValue: _i5.Future<List<_i3.Album>>.value(<_i3.Album>[]),
      ) as _i5.Future<List<_i3.Album>>);

  @override
  _i5.Future<void> clearCache() => (super.noSuchMethod(
        Invocation.method(
          #clearCache,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void clearCacheEntry(
    String? endpoint, [
    Map<String, String>? params,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #clearCacheEntry,
          [
            endpoint,
            params,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearExpiredCache() => super.noSuchMethod(
        Invocation.method(
          #clearExpiredCache,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  Map<String, dynamic> getCacheStats() => (super.noSuchMethod(
        Invocation.method(
          #getCacheStats,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  void invalidateAlbumCache() => super.noSuchMethod(
        Invocation.method(
          #invalidateAlbumCache,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void invalidateArtistCache() => super.noSuchMethod(
        Invocation.method(
          #invalidateArtistCache,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void invalidateSearchCache() => super.noSuchMethod(
        Invocation.method(
          #invalidateSearchCache,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateNetworkConfig(_i2.NetworkConfig? newConfig) => super.noSuchMethod(
        Invocation.method(
          #updateNetworkConfig,
          [newConfig],
        ),
        returnValueForMissingStub: null,
      );

  @override
  Map<String, dynamic> getNetworkStats() => (super.noSuchMethod(
        Invocation.method(
          #getNetworkStats,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
